Name:           ros-melodic-jackal-gazebo
Version:        0.3.0
Release:        1%{?dist}
Summary:        ROS jackal_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/jackal_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-plugins
Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-gazebo-ros-control
Requires:       ros-melodic-hector-gazebo-plugins
Requires:       ros-melodic-jackal-control >= 0.5
Requires:       ros-melodic-jackal-description >= 0.5
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslaunch

%description
Launchfiles to use Jackal in Gazebo.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Jul 22 2019 Mike Purvis <mpurvis@clearpathrobotics.com> - 0.3.0-1
- Autogenerated by Bloom

